<?php

/**
 * TipTapEditor system settings lexicon (ru).
 */

$_lang['area_tiptapeditor.main'] = 'Интерфейс';
$_lang['area_tiptapeditor.content'] = 'Содержимое';
$_lang['area_tiptapeditor.modx'] = 'Интеграция с MODX';
$_lang['area_tiptapeditor.system'] = 'Система';

$_lang['setting_tiptapeditor.toolbar'] = 'Панель инструментов';
$_lang['setting_tiptapeditor.toolbar_desc'] = 'Кнопки через пробел, группы через «|». Пример: undo redo | heading | bold italic | link image.';
$_lang['setting_tiptapeditor.profiles'] = 'Профили';
$_lang['setting_tiptapeditor.profiles_desc'] = 'JSON-объект именованных профилей, например {"simple": {"toolbar": "bold italic link"}}. Профиль переопределяет toolbar и функции.';
$_lang['setting_tiptapeditor.default_profile'] = 'Профиль по умолчанию';
$_lang['setting_tiptapeditor.default_profile_desc'] = 'Профиль, который используется, если не задан другой.';
$_lang['setting_tiptapeditor.content_profile'] = 'Профиль поля content';
$_lang['setting_tiptapeditor.content_profile_desc'] = 'Профиль для поля content ресурса. Пусто — профиль по умолчанию.';
$_lang['setting_tiptapeditor.tv_profiles'] = 'Профили TV';
$_lang['setting_tiptapeditor.tv_profiles_desc'] = 'Имя TV → профиль: JSON-объект, например {"introtext": "simple"}, или пары имя=профиль по одной в строке или через запятую.';
$_lang['setting_tiptapeditor.heading_levels'] = 'Уровни заголовков';
$_lang['setting_tiptapeditor.heading_levels_desc'] = 'Доступные уровни заголовков через запятую.';
$_lang['setting_tiptapeditor.bubble_menu'] = 'Всплывающее меню';
$_lang['setting_tiptapeditor.bubble_menu_desc'] = 'Показывать меню форматирования над выделенным текстом.';
$_lang['setting_tiptapeditor.floating_menu'] = 'Плавающее меню';
$_lang['setting_tiptapeditor.floating_menu_desc'] = 'Показывать меню вставки на пустом абзаце.';
$_lang['setting_tiptapeditor.slash_commands'] = 'Slash-команды';
$_lang['setting_tiptapeditor.slash_commands_desc'] = 'Ввод «/» на пустой строке открывает меню блоков.';
$_lang['setting_tiptapeditor.statusbar'] = 'Строка состояния';
$_lang['setting_tiptapeditor.statusbar_desc'] = 'Показывать количество слов и символов и путь текущего элемента.';
$_lang['setting_tiptapeditor.sticky_toolbar'] = 'Закреплённая панель';
$_lang['setting_tiptapeditor.sticky_toolbar_desc'] = 'Панель инструментов остаётся видимой при прокрутке.';
$_lang['setting_tiptapeditor.enable_fullscreen'] = 'Полноэкранный режим';
$_lang['setting_tiptapeditor.enable_fullscreen_desc'] = 'Разрешить кнопку полноэкранного режима (выход — Esc).';
$_lang['setting_tiptapeditor.min_height'] = 'Минимальная высота';
$_lang['setting_tiptapeditor.min_height_desc'] = 'Минимальная высота редактора в пикселях.';
$_lang['setting_tiptapeditor.max_height'] = 'Максимальная высота';
$_lang['setting_tiptapeditor.max_height_desc'] = 'Максимальная высота при автоувеличении, в пикселях. 0 — без ограничения.';
$_lang['setting_tiptapeditor.default_height'] = 'Высота по умолчанию';
$_lang['setting_tiptapeditor.default_height_desc'] = 'Высота редактора в пикселях, если автоувеличение выключено.';
$_lang['setting_tiptapeditor.autogrow'] = 'Автоувеличение';
$_lang['setting_tiptapeditor.autogrow_desc'] = 'Редактор растёт вместе с содержимым до максимальной высоты.';
$_lang['setting_tiptapeditor.content_css'] = 'CSS содержимого';
$_lang['setting_tiptapeditor.content_css_desc'] = 'Список CSS-файлов сайта через запятую для отображения содержимого в редакторе, например /assets/css/content.css,/assets/css/article.css.';
$_lang['setting_tiptapeditor.enable_tables'] = 'Таблицы';
$_lang['setting_tiptapeditor.enable_tables_desc'] = 'Таблицы в редакторе: кнопка таблицы и панель таблицы. Если выключено, контент с таблицами остаётся в обычном текстовом поле.';
$_lang['setting_tiptapeditor.enable_images'] = 'Изображения';
$_lang['setting_tiptapeditor.enable_images_desc'] = 'Включить изображения.';
$_lang['setting_tiptapeditor.enable_iframe'] = 'Iframe и встраивание';
$_lang['setting_tiptapeditor.enable_iframe_desc'] = 'Включить iframe и встраивание видео.';
$_lang['setting_tiptapeditor.iframe_allowed_attributes'] = 'Разрешённые атрибуты iframe';
$_lang['setting_tiptapeditor.iframe_allowed_attributes_desc'] = 'Список разрешённых атрибутов iframe через запятую. Обработчики событий (on*) удаляются всегда.';
$_lang['setting_tiptapeditor.iframe_allowed_hosts'] = 'Разрешённые хосты iframe';
$_lang['setting_tiptapeditor.iframe_allowed_hosts_desc'] = 'Список хостов, разрешённых в src у iframe, через запятую. Пусто — любой хост.';
$_lang['setting_tiptapeditor.paste_as_text'] = 'Вставка как текст';
$_lang['setting_tiptapeditor.paste_as_text_desc'] = 'Вставлять содержимое буфера обмена как простой текст.';
$_lang['setting_tiptapeditor.image_classes'] = 'Пресеты классов изображений';
$_lang['setting_tiptapeditor.image_classes_desc'] = 'Классы для изображений: JSON-объект {"css-класс": "Название"} или список классов через запятую.';
$_lang['setting_tiptapeditor.link_classes'] = 'Пресеты классов ссылок';
$_lang['setting_tiptapeditor.link_classes_desc'] = 'CSS-классы для диалога ссылки: JSON-объект {"css-класс": "Название"} или список классов через запятую. Пусто — свободное текстовое поле.';
$_lang['setting_tiptapeditor.paragraph_classes'] = 'Пресеты классов абзацев';
$_lang['setting_tiptapeditor.paragraph_classes_desc'] = 'Классы для абзацев: JSON-объект {"css-класс": "Название"} или список классов через запятую.';
$_lang['setting_tiptapeditor.table_classes'] = 'Пресеты классов таблиц';
$_lang['setting_tiptapeditor.table_classes_desc'] = 'CSS-классы в диалоге таблицы: JSON-объект {"css-класс": "Название"} (в одной записи можно несколько классов) или список через запятую.';
$_lang['setting_tiptapeditor.preserve_style_attribute'] = 'Сохранять атрибут style';
$_lang['setting_tiptapeditor.preserve_style_attribute_desc'] = 'Сохранять существующие атрибуты style без изменений. Выключите, чтобы удалять inline-стили.';
$_lang['setting_tiptapeditor.protect_modx_syntax'] = 'Защита тегов MODX';
$_lang['setting_tiptapeditor.protect_modx_syntax_desc'] = 'Сохранять теги MODX, например [[*pagetitle]] и [[!snippet? ...]], без изменений: они показываются защищёнными плашками, не экранируются и не разбиваются, в том числе при правке текста вокруг.';
$_lang['setting_tiptapeditor.protect_fenom_syntax'] = 'Защита Fenom';
$_lang['setting_tiptapeditor.protect_fenom_syntax_desc'] = 'Сохранять конструкции Fenom, например {$var}, {if}...{/if} и {foreach}, без изменений: они показываются защищёнными плашками или карточками и не экранируются. «{ » с пробелом остаётся текстом (CSS, JSON).';
$_lang['setting_tiptapeditor.fenom_tags'] = 'Дополнительные теги Fenom';
$_lang['setting_tiptapeditor.fenom_tags_desc'] = 'Имена собственных тегов или функций Fenom через запятую (myTag, other), которые нужно защищать помимо встроенных ключевых слов (if, foreach, set, include, ...).';
$_lang['setting_tiptapeditor.modx_autocomplete'] = 'Автодополнение MODX';
$_lang['setting_tiptapeditor.modx_autocomplete_desc'] = 'Подсказывать поля, сниппеты, чанки и настройки при вводе тегов MODX.';
$_lang['setting_tiptapeditor.fenom_autocomplete'] = 'Автодополнение Fenom';
$_lang['setting_tiptapeditor.fenom_autocomplete_desc'] = 'Подсказывать основные переменные Fenom при вводе.';
$_lang['setting_tiptapeditor.links_across_contexts'] = 'Ссылки между контекстами';
$_lang['setting_tiptapeditor.links_across_contexts_desc'] = 'Нет (по умолчанию): поиск ресурса MODX в диалоге ссылки ищет только в контексте редактируемого ресурса. Да: во всех контекстах, доступных пользователю (кроме mgr).';
$_lang['setting_tiptapeditor.resource_link_format'] = 'Формат ссылки на ресурс';
$_lang['setting_tiptapeditor.resource_link_format_desc'] = 'href для ресурса MODX, выбранного в диалоге ссылки. {id} — ID ресурса (обязательно); также заменяются {context} и {uri}. По умолчанию: [[~{id}]].';
$_lang['setting_tiptapeditor.media_source'] = 'Источник файлов';
$_lang['setting_tiptapeditor.media_source_desc'] = 'ID источника файлов для файлового браузера. Пусто — источник контекста по умолчанию или источник TV.';
$_lang['setting_tiptapeditor.media_url_mode'] = 'Формат URL файлов';
$_lang['setting_tiptapeditor.media_url_mode_desc'] = '«relative» (по умолчанию) — URL в точности как вернул файловый менеджер MODX, как в TV «Изображение»; «root» — к относительным URL добавляется base URL сайта (например, /assets/img/a.jpg). Абсолютные URL (S3 и другие удалённые источники) всегда сохраняются как есть.';
$_lang['setting_tiptapeditor.upload_enabled'] = 'Загрузка перетаскиванием и вставкой';
$_lang['setting_tiptapeditor.upload_enabled_desc'] = 'Загружать перетащенные и вставленные в редактор изображения в источник файлов поля, в папку tiptapeditor.upload_path. Загрузка идёт через штатную загрузку MODX (право file_upload, политики источника, разрешённые типы файлов и upload_maxsize). Изображения никогда не сохраняются в base64.';
$_lang['setting_tiptapeditor.external_config'] = 'Внешняя конфигурация';
$_lang['setting_tiptapeditor.external_config_desc'] = 'Путь к JSON-файлу с дополнительной конфигурацией, например {core_path}config/tiptapeditor.json. Читаются только данные, код не выполняется.';
$_lang['setting_tiptapeditor.debug'] = 'Режим отладки';
$_lang['setting_tiptapeditor.debug_desc'] = 'Выводить диагностические сообщения в консоль браузера и журнал ошибок MODX.';
$_lang['setting_tiptapeditor.upload_path'] = 'Папка загрузки';
$_lang['setting_tiptapeditor.upload_path_desc'] = 'Папка в источнике файлов поля для перетащенных и вставленных изображений, например assets/uploads/.';
$_lang['setting_tiptapeditor.enable_gallery'] = 'Галереи';
$_lang['setting_tiptapeditor.enable_gallery_desc'] = 'Включить кнопку «Галерея»: несколько изображений по шаблону (сетка, слайдер…).';
$_lang['setting_tiptapeditor.gallery_template'] = 'Шаблон галереи';
$_lang['setting_tiptapeditor.gallery_template_desc'] = 'Шаблон новых галерей: grid (сетка), slider (разметка Swiper), images (только изображения) или имя из tiptapeditor.gallery_templates.';
$_lang['setting_tiptapeditor.gallery_templates'] = 'Свои шаблоны галерей';
$_lang['setting_tiptapeditor.gallery_templates_desc'] = 'JSON с дополнительными шаблонами, например {"cards": {"label": "Карточки", "wrapper": "<ul class=\\"cards\\">{items}</ul>", "item": "<li>{image}{caption}</li>"}}. {items} — изображения, {image} — изображение (со ссылкой, если включено увеличение), {caption} — <figcaption> с подписью. Скрипты и атрибуты on* удаляются.';
$_lang['setting_tiptapeditor.lightbox'] = 'Увеличение изображений по клику';
$_lang['setting_tiptapeditor.lightbox_desc'] = 'Новые изображения и галереи получают ссылку на изображение вокруг картинки (<figure><a href="…"><img></a></figure>) для скрипта-лайтбокса на сайте. В диалоге включается и выключается для каждой картинки и галереи.';
$_lang['setting_tiptapeditor.lightbox_attribute'] = 'Атрибут лайтбокса';
$_lang['setting_tiptapeditor.lightbox_attribute_desc'] = 'Атрибут, который ищет ваш скрипт-лайтбокс, например data-fancybox (Fancybox), data-lightbox, data-gallery. У одиночного изображения он без значения, у галереи — с именем группы (data-fancybox="gallery-3fa9c1"). Пусто — обычная ссылка.';
$_lang['setting_tiptapeditor.lightbox_label'] = 'Подпись ссылки увеличения';
$_lang['setting_tiptapeditor.lightbox_label_desc'] = 'aria-label ссылки, {alt} — альтернативный текст или подпись. Пусто — «Открыть изображение: {alt}» на языке менеджера.';
