<?php

/**
 * TipTapEditor system settings lexicon (en).
 */

$_lang['area_tiptapeditor.main'] = 'Interface';
$_lang['area_tiptapeditor.content'] = 'Content';
$_lang['area_tiptapeditor.modx'] = 'MODX integration';
$_lang['area_tiptapeditor.system'] = 'System';

$_lang['setting_tiptapeditor.toolbar'] = 'Toolbar';
$_lang['setting_tiptapeditor.toolbar_desc'] = 'Toolbar buttons separated by spaces, groups separated by "|". Example: undo redo | heading | bold italic | link image.';
$_lang['setting_tiptapeditor.profiles'] = 'Profiles';
$_lang['setting_tiptapeditor.profiles_desc'] = 'JSON object of named editor profiles, e.g. {"simple": {"toolbar": "bold italic link"}}. A profile overrides the toolbar and features.';
$_lang['setting_tiptapeditor.default_profile'] = 'Default profile';
$_lang['setting_tiptapeditor.default_profile_desc'] = 'Profile used when no other profile applies.';
$_lang['setting_tiptapeditor.content_profile'] = 'Content profile';
$_lang['setting_tiptapeditor.content_profile_desc'] = 'Profile for the resource content field. Empty means the default profile.';
$_lang['setting_tiptapeditor.tv_profiles'] = 'TV profiles';
$_lang['setting_tiptapeditor.tv_profiles_desc'] = 'TV name → profile: a JSON object such as {"introtext": "simple"}, or name=profile pairs, one per line or comma separated.';
$_lang['setting_tiptapeditor.heading_levels'] = 'Heading levels';
$_lang['setting_tiptapeditor.heading_levels_desc'] = 'Comma separated heading levels available in the editor.';
$_lang['setting_tiptapeditor.bubble_menu'] = 'Bubble menu';
$_lang['setting_tiptapeditor.bubble_menu_desc'] = 'Show a formatting menu above selected text.';
$_lang['setting_tiptapeditor.floating_menu'] = 'Floating menu';
$_lang['setting_tiptapeditor.floating_menu_desc'] = 'Show an insert menu on an empty paragraph.';
$_lang['setting_tiptapeditor.slash_commands'] = 'Slash commands';
$_lang['setting_tiptapeditor.slash_commands_desc'] = 'Typing "/" on an empty line opens the block menu.';
$_lang['setting_tiptapeditor.statusbar'] = 'Status bar';
$_lang['setting_tiptapeditor.statusbar_desc'] = 'Show word and character count and the current element path.';
$_lang['setting_tiptapeditor.sticky_toolbar'] = 'Sticky toolbar';
$_lang['setting_tiptapeditor.sticky_toolbar_desc'] = 'Keep the toolbar visible while scrolling long content.';
$_lang['setting_tiptapeditor.enable_fullscreen'] = 'Fullscreen';
$_lang['setting_tiptapeditor.enable_fullscreen_desc'] = 'Allow the fullscreen mode button (Esc exits).';
$_lang['setting_tiptapeditor.min_height'] = 'Minimum height';
$_lang['setting_tiptapeditor.min_height_desc'] = 'Minimum editor height in pixels.';
$_lang['setting_tiptapeditor.max_height'] = 'Maximum height';
$_lang['setting_tiptapeditor.max_height_desc'] = 'Maximum editor height in pixels when autogrow is on. 0 means unlimited.';
$_lang['setting_tiptapeditor.default_height'] = 'Default height';
$_lang['setting_tiptapeditor.default_height_desc'] = 'Editor height in pixels when autogrow is off.';
$_lang['setting_tiptapeditor.autogrow'] = 'Autogrow';
$_lang['setting_tiptapeditor.autogrow_desc'] = 'Grow the editor with its content up to the maximum height.';
$_lang['setting_tiptapeditor.content_css'] = 'Content CSS';
$_lang['setting_tiptapeditor.content_css_desc'] = 'Comma separated list of site stylesheets applied to the content inside the editor, e.g. /assets/css/content.css,/assets/css/article.css.';
$_lang['setting_tiptapeditor.enable_tables'] = 'Tables';
$_lang['setting_tiptapeditor.enable_tables_desc'] = 'Tables in the editor: table button, table toolbar. When off, content with tables stays in the plain text field.';
$_lang['setting_tiptapeditor.enable_images'] = 'Images';
$_lang['setting_tiptapeditor.enable_images_desc'] = 'Enable images.';
$_lang['setting_tiptapeditor.enable_iframe'] = 'Iframes and embeds';
$_lang['setting_tiptapeditor.enable_iframe_desc'] = 'Enable iframe and video embeds.';
$_lang['setting_tiptapeditor.iframe_allowed_attributes'] = 'Allowed iframe attributes';
$_lang['setting_tiptapeditor.iframe_allowed_attributes_desc'] = 'Comma separated whitelist of iframe attributes. Event handler attributes (on*) are always removed.';
$_lang['setting_tiptapeditor.iframe_allowed_hosts'] = 'Allowed iframe hosts';
$_lang['setting_tiptapeditor.iframe_allowed_hosts_desc'] = 'Comma separated list of hosts allowed in iframe src. Empty allows any host.';
$_lang['setting_tiptapeditor.paste_as_text'] = 'Paste as text';
$_lang['setting_tiptapeditor.paste_as_text_desc'] = 'Paste clipboard content as plain text.';
$_lang['setting_tiptapeditor.image_classes'] = 'Image class presets';
$_lang['setting_tiptapeditor.image_classes_desc'] = 'Classes offered for images: a JSON object {"css-class": "Label"} or a comma separated list of classes.';
$_lang['setting_tiptapeditor.link_classes'] = 'Link class presets';
$_lang['setting_tiptapeditor.link_classes_desc'] = 'CSS classes offered in the link dialog: a JSON object {"css-class": "Label"} or a comma separated list of classes. Empty: free text field.';
$_lang['setting_tiptapeditor.paragraph_classes'] = 'Paragraph class presets';
$_lang['setting_tiptapeditor.paragraph_classes_desc'] = 'Classes offered for paragraphs: a JSON object {"css-class": "Label"} or a comma separated list of classes.';
$_lang['setting_tiptapeditor.table_classes'] = 'Table class presets';
$_lang['setting_tiptapeditor.table_classes_desc'] = 'CSS classes offered in the table dialog: JSON object {"css-class": "Label"} (several classes per entry are allowed) or a comma separated list.';
$_lang['setting_tiptapeditor.preserve_style_attribute'] = 'Preserve style attributes';
$_lang['setting_tiptapeditor.preserve_style_attribute_desc'] = 'Keep existing style attributes unchanged. Turn off to drop inline styles.';
$_lang['setting_tiptapeditor.protect_modx_syntax'] = 'Protect MODX tags';
$_lang['setting_tiptapeditor.protect_modx_syntax_desc'] = 'Keep MODX tags like [[*pagetitle]] and [[!snippet? ...]] exactly as written: shown as protected badges, never escaped or split, also when the text around them is edited.';
$_lang['setting_tiptapeditor.protect_fenom_syntax'] = 'Protect Fenom';
$_lang['setting_tiptapeditor.protect_fenom_syntax_desc'] = 'Keep Fenom constructs like {$var}, {if}...{/if} and {foreach} exactly as written: shown as protected badges or cards, never escaped. "{ " with a space stays text (CSS, JSON).';
$_lang['setting_tiptapeditor.fenom_tags'] = 'Extra Fenom tags';
$_lang['setting_tiptapeditor.fenom_tags_desc'] = 'Comma separated names of your own Fenom tags or functions (myTag, other) to protect in addition to the built-in keywords (if, foreach, set, include, ...).';
$_lang['setting_tiptapeditor.modx_autocomplete'] = 'MODX autocomplete';
$_lang['setting_tiptapeditor.modx_autocomplete_desc'] = 'Suggest fields, snippets, chunks and settings while typing MODX tags.';
$_lang['setting_tiptapeditor.fenom_autocomplete'] = 'Fenom autocomplete';
$_lang['setting_tiptapeditor.fenom_autocomplete_desc'] = 'Suggest common Fenom variables while typing.';
$_lang['setting_tiptapeditor.links_across_contexts'] = 'Links across contexts';
$_lang['setting_tiptapeditor.links_across_contexts_desc'] = 'No (default): the MODX resource search in the link dialog finds resources in the context of the edited resource only. Yes: in all contexts the user may load (never mgr).';
$_lang['setting_tiptapeditor.resource_link_format'] = 'Resource link format';
$_lang['setting_tiptapeditor.resource_link_format_desc'] = 'href written for a MODX resource chosen in the link dialog. {id} is the resource ID (required); {context} and {uri} are also replaced. Default: [[~{id}]].';
$_lang['setting_tiptapeditor.media_source'] = 'Media source';
$_lang['setting_tiptapeditor.media_source_desc'] = 'Media source ID for the file browser. Empty uses the context default or the TV source.';
$_lang['setting_tiptapeditor.media_url_mode'] = 'Media URL mode';
$_lang['setting_tiptapeditor.media_url_mode_desc'] = '"relative" (default) stores the URL exactly as the MODX Media Browser returns it, like the Image TV; "root" prefixes relative URLs with the site base URL (e.g. /assets/img/a.jpg). Absolute URLs (S3 and other remote sources) are always kept as they are.';
$_lang['setting_tiptapeditor.upload_enabled'] = 'Upload dropped and pasted images';
$_lang['setting_tiptapeditor.upload_enabled_desc'] = 'Upload images dropped or pasted into the editor into the field\'s Media Source, folder tiptapeditor.upload_path. Uploads go through the MODX file upload (permission file_upload, the source\'s policies, allowed file types and upload_maxsize apply). Images are never stored as base64.';
$_lang['setting_tiptapeditor.external_config'] = 'External config';
$_lang['setting_tiptapeditor.external_config_desc'] = 'Path to a JSON file with additional configuration, e.g. {core_path}config/tiptapeditor.json. Only data is read, no code is executed.';
$_lang['setting_tiptapeditor.debug'] = 'Debug mode';
$_lang['setting_tiptapeditor.debug_desc'] = 'Write diagnostic messages to the browser console and the MODX error log.';
$_lang['setting_tiptapeditor.upload_path'] = 'Upload folder';
$_lang['setting_tiptapeditor.upload_file_prefix'] = 'Upload file name prefix';
$_lang['setting_tiptapeditor.upload_file_prefix_desc'] = 'Added before the name of uploaded images, e.g. {id}- gives 15-photo-x7k2q9.jpg. Same placeholders as the upload folder.';
$_lang['setting_tiptapeditor.upload_rand_length'] = 'Length of {rand}';
$_lang['setting_tiptapeditor.upload_rand_length_desc'] = 'Number of characters of the {rand} placeholder (1–32).';
$_lang['setting_tiptapeditor.upload_path_desc'] = 'Folder in the field\'s Media Source for uploaded images, e.g. assets/uploads/ or assets/uploads/{y}/{m}/{id}/. Placeholders: {id}, {pid} (parent ID), {alias}, {palias} (parent alias), {context}, {tid} (TV ID, empty for the content field), {uid} (user ID), {rand} (random string), {t} (timestamp), {y}, {m}, {d}, {h}, {i}, {s}. {id} and {alias} need a saved resource.';
$_lang['setting_tiptapeditor.enable_gallery'] = 'Galleries';
$_lang['setting_tiptapeditor.enable_gallery_desc'] = 'Enable the gallery button: several images with a template (grid, slider, …).';
$_lang['setting_tiptapeditor.gallery_template'] = 'Gallery template';
$_lang['setting_tiptapeditor.gallery_template_desc'] = 'Template of new galleries: grid, slider (Swiper markup), images, or a name from tiptapeditor.gallery_templates.';
$_lang['setting_tiptapeditor.gallery_templates'] = 'Own gallery templates';
$_lang['setting_tiptapeditor.gallery_templates_desc'] = 'JSON with more templates, e.g. {"cards": {"label": "Cards", "wrapper": "<ul class=\\"cards\\">{items}</ul>", "item": "<li>{image}{caption}</li>"}}. {items} = the pictures, {image} = the image (with its link when "open larger" is on), {caption} = <figcaption> with the caption. Scripts and on* attributes are removed.';
$_lang['setting_tiptapeditor.lightbox'] = 'Open images larger on click';
$_lang['setting_tiptapeditor.lightbox_desc'] = 'New images and galleries get a link to the image around the picture (<figure><a href="…"><img></a></figure>) for a lightbox script on the site. Can be switched per image and gallery in the dialog.';
$_lang['setting_tiptapeditor.lightbox_attribute'] = 'Lightbox attribute';
$_lang['setting_tiptapeditor.lightbox_attribute_desc'] = 'Attribute your lightbox script looks for, e.g. data-fancybox (Fancybox), data-lightbox, data-gallery. A single image gets it without a value, a gallery with its group name (data-fancybox="gallery-3fa9c1"). Empty: a plain link.';
$_lang['setting_tiptapeditor.lightbox_label'] = 'Lightbox link label';
$_lang['setting_tiptapeditor.lightbox_label_desc'] = 'aria-label of the link, {alt} = the alt text or caption. Empty: "Open image: {alt}" in the manager language.';
